### ISSUE TITLE
[Req] Command line switches

### ISSUE THREAD

**Issue by Janca** [SerGreen/Appacker#1]
Would it be possible to add a command line switches to the Apppacker main executable.

Switches could be:

**`-s --src`** - Application directory to pack.
**`-d --dst`** - Destination where packed app will be created.
**`-e --exe`** - Main executable. This is the application that will launch whenever the packed app extracts itself.
**`-r --self-repack`** - Sets the packed application to refresh itself after the main executable closes. Refreshing adds and replaces files in the packed executable with those created and modified during runtime.
**`-i --icon`** - Packed application icon.

This would allow me to use this application in my workflow.

-Thanks

**Comment by SerGreen** [comment]
Done!
