### ISSUE TITLE
Move Registry Settings to INI File, Remember Settings (Hide Launch Popup, Window Position+Size, etc.)

### ISSUE THREAD

**Issue by hairycactus** [SerGreen/Appacker#14]
Regarding the new `Visual C++ Runtime 2005 x86 not found!` reminder popup that appears upon every launch, is it possible to have a tick option `Do not show again` for the popup, & remember this setting ? (User can still click on the red exclamation mark icon to manually show the popup on-demand.)

### Mockup Screenshot:
![Appacker Launch Nagscreen](https://i.imgur.com/jekMdsb.png)

Appacker already writes a non-user-configured setting in the registry at:

```
HKCU\Software\SerGreen\Appacker  
=> Language = en-US 
```

How about moving all settings to an INI file within Appacker's folder, so that it doesn't write to the registry or elsewhere in the filesystem ?

Other settings good to have include:

1. **Remembering window position & size**  
Currently, Appacker's main window position changes randomly upon every launch.

2. **Options in the `Advanced Options` section**  
Currently, Appacker does not seem to remember any non-default option here.

**Tested:** Appacker v1.3.9 (23 Oct 2021)   
**OS:** Win 10 x64

Thanks !

**Comment by SerGreen** [comment]
Issue solved with [v1.3.10](https://github.com/SerGreen/Appacker/releases/tag/v1.3.10).

**Comment by hairycactus** [comment]
> Download the default Appacker.ini file from release as well or it will save language in the registry at the start, before you will be able to generate your own ini file.

Just tested the final v1.3.10 release. Appacker now retains its settings via the new INI file. Thanks !

That being said, from my experience of using hundreds of portable programs, it's rather unusual to have to download a default INI separately.

If not already (usually) supplied with the release package, the alternative is for the user to create an empty INI file using a text editor, place it beside the executable file in the same folder, launch the program, & let the program write what needs to be written to the said INI file w/o it ever touching the registry &/or outside of its working folder.

I'm not sure if Appacker behaves like a typical portable program -- so far, the workflow has been rather atypical. So below are some queries ...

1. If Appacker introduces **new settings in a future release** (eg. a hypothetical `Do not warn on output file overwrite`), can we launch the program with the **existing INI file**, such that all new settings subsequently configured would automatically be written to the INI file ? Or do we need to download a new default INI file (with the fields for the new settings) & redo all the previous settings ?

2. Would the default INI file be supplied & & its usage instructions spelt out with every new release ? (I assume new users generally look at the latest release, & don't check the older ones for extra required files.)


> Why delete it? Is there anything wrong with storing application configuration in registry?

- A portable program should not be storing essential settings to the registry &/or filesystem outside of the application's folder. Otherwise, the program is not portable, but merely no-install.

- The (now-defunct) Language setting in the registry is superfluous -- its absence does not affect the program's portability. But imagine running this on someone else's PC or the public library PC ... Even disregarding user privacy issues, other parties (esp. the library IT tech) might consider its presence junk.

Hope the above explains ...

**Comment by SerGreen** [comment]
Okay, i understand the reason behind not wanting registry entries. I think i just never designed the app to be portable, the only criteria was to make it a single file application but also be able to remember settings, hence why i didn't want to use an additional config file. I guess i'll make registry saves an opt-in feature in the future release (if there will be one).  

As for the questions:  
1. You don't __*have*__ to download the INI file separately, you can click a button in the options and the app will generate INI file itself. Creating an empty `appacker.ini` file and placing it in the same folder is also an option. If any file named `appacker.ini` is present in the same folder as `appacker.exe` then it will not write to the registry.  
1. Future releases should be able to work with old INI files. It's designed to be able to digest broken files too (it uses default values when it can't find some option in the INI file). You won't have to download new INI files, the app generates and saves a valid INI file when you close the app (only if `appacker.ini` file already existed before you launched the app).  
2. No, i don't plan to supply default INI files with future releases, user can generate this file manually by clicking a button in Advanced Options. And future releases won't try to use registry anyways, unless user will choose so.
