### ISSUE TITLE
CLI Exit Issue

### ISSUE THREAD

**Issue by Janca** [SerGreen/Appacker#2]
The application does not exit properly. You must press `Enter` in the command prompt after the application should have exited to actually get the application to exit. This is happens whether an error occurs, when packing is successful or even just displaying the help message.

This is causing in issue in my workflow as I am waiting for exit signals. Although this isn't the place, thanks for your work and commitment to this project.

**Comment by SerGreen** [comment]
God dammit, i closed #1 in the commit message instead of #2... _Ok Google, how to change commit message **easily**?_ .___.
Anyways, [update with the fix should be up](https://github.com/SerGreen/Appacker/releases/latest). Cheers!
