### ISSUE TITLE
unpacker

### ISSUE THREAD

**Issue by pvzlawnmower** [SerGreen/Appacker#23]
hi where is the unpaker ,i'm sorry that I couldn'd found it.how to unpack exe files?

**Comment by SerGreen** [comment]
You can unpack exe files produced by Appacker by executing those exe files (double click), they unpack by themselves. Unpacker is built into such exe files and it performs all of the unpacking automatically when you start it, it puts all of the unpacked files into a temporary directory in `AppData\Local\Temp\`.  

If that's not what you are asking then please describe in detail all of the steps of what you try to do.

**Comment by pvzlawnmower** [comment]
Is there any way to unpack the exe and get the files in it?

**Comment by SerGreen** [comment]
Well, _technically_ yes. Launch the packed exe and while it's still running open `C:\Users\<username>\AppData\Local\Temp\` and find there a folder named like `<NameOfThePackedApp_random-numbers-and-letters>` (try sorting by date modified):  
![image](https://user-images.githubusercontent.com/4000373/210702923-4118c0b6-9b3f-4d65-87d1-7860de51c121.png)  

Inside that folder you will find all of the unpacked files (assuming the app was set to unpack into a temp folder, which is default, however).  

That temp directory is erased once the app is closed, so it gets tricky if your packed application doesn't stay open indefinitely and closes before you can find files in the temp directory. One could try to halt the execution using a debugger, i suppose.

**Comment by pvzlawnmower** [comment]
Ok,I know.thank you.
