### ISSUE TITLE
Info: Bitdefender detect it as Virus: Gen:Suspicious.Cloud.2.km8@a8@ENfc 

### ISSUE THREAD

**Issue by scysys** [SerGreen/Appacker#27]

**Comment by zwzodo** [comment]
Yes, it Happens With Most Antiviruses as it suspects the app is malware because of the way it works it extract files from inside the .exe and add them into temp or Same folder or whatever you choosed and iisn't't a virus and if you want to make it run anyway then add the .exe in exceptions
