### ISSUE TITLE
Output executable's icon does not have all the resolutions contained in the ico file

### ISSUE THREAD

**Issue by babak-f** [SerGreen/Appacker#6]
I have an ico file that contains the resolutions 16x16, 32x32, 48x48, and 256x256. When I set it as the icon of the executable, the resulting executable's icon does not have the 256x256 resolution. More specifically, it has a smaller resolution, maybe 48x48 or 32x32 - but definitely not 256x256. 

I used the GUI.

**Comment by SerGreen** [comment]
Thank you for reporting the bugs.  
Originally i completely neglected the multi-sized nature of icons and treated them as plain images, that's where the low resolution problems and that weird crash with 256x256 icon (issue #5) came from.  

I remade a piece of code related to loading icons and now it seems to be properly working with icons that have multiple resolutions, and the bug with only-256 icon also does not occur anymore. I will upload the updated version shortly.
