### ISSUE TITLE
hiding appacker unpacking bar?

### ISSUE THREAD

**Issue by valtyr-nidavellir** [SerGreen/Appacker#8]
Quick question for ya.
Is it possible to hide the unpacking progress bar on application execution?

**Comment by SerGreen** [comment]
Currently there's no option for that unfortunately.  
It is normally hidden and shows only when unpacking takes more than a second, to show that it's still launching. How long it takes for the progress bar to appear is determined by the `SPLASH_POPUP_DELAY` constant in `/Unpacker/Unpacker Program.cs`, but there's no way to set it within the app for now.

**Comment by valtyr-nidavellir** [comment]
I'll try compiling with that constant adjusted to a higher value. Thanks for the info.

**Comment by SerGreen** [comment]
You can also change the `if` condition where it's used (in the same file) to something like `if (false)` to disable progress bar altogether, if you want.

**Comment by valtyr-nidavellir** [comment]
Thanks for the suggestion.
